###
POST http://localhost:3000/users

{
    "first_name" : "jang",
    "last_name" : "seonghyun",
    "email" : "abc7468@naver.com"
}

###

GET http://localhost:3000/users/2

{
    "first_name" : "jang",
    "last_name" : "seonghyun",
    "email" : "abc7468@naver.com"
}
