###
GET http://localhost:8080/api/v1/task/10

###
POST http://localhost:8080/api/v1/task/1

{
    "id": 4,
    
}

###
PUT http://localhost:8080/api/v1/task/1

###
DELETE http://localhost:8080/api/v1/task/2

